# Generated by Django 6.0.6 on 2026-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_cameraimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='recommended_trip_type',
            field=models.CharField(choices=[('City', 'City'), ('Nature', 'Nature'), ('Beach', 'Beach'), ('Road Trip', 'Road Trip'), ('Beginner Friendly', 'Beginner Friendly'), ('Low Light', 'Low Light')], default='Beginner Friendly', max_length=50),
        ),
    ]
